import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import Image from "next/image";
import React, { useState, useEffect } from 'react';
import axios from 'axios';
//import tmdb from "../public/tmdb.svg";


export default function Home({ }) {
    const [videos, setVideosContent] = useState([]);
  

  useEffect(() => {
      axios.get('videos.json')
          .then(res => setVideosContent(res.data))
          .catch(error => console.error(error));
  
  }, []);

  // .replace(/\n/g, "<br>")
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={videos} />
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const genre = context.query.genre;
//   const request = await fetch(
//     `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url
//     }`
//   ).then((res) => res.json());

//   return {
//     props: {
//       results: request.results,
//     },
//   };
// }